- name: Install core packages
  become: true
  ansible.builtin.apt:
    name:
      - bat
      - cargo
      - ccache
      - clang
      - clipit
      - feh
      - fonts-firacode
      - fonts-font-awesome
      - fzf
      - gimp
      - golang
      - htop
      - i3-wm
      - kitty
      - nodejs
      - npm
      - picom
      - python3-pip
      - ripgrep
      - rofi
      - rustc
      - texstudio
      - timeshift
      - tmux
      - xbacklight
      - xclip
      - yakuake
      - zeal
      - zsh
  tags:
    - install
    - core

# - name: Install pytest and dependencies
#   become: true
#   ansible.builtin.apt:
#     name:
#       - python3-pip  # Make sure pip is installed
#   tasks:
#     - name: Install pytest and dependencies via pip
#       pip:
#         name:
#           - pytest
#           - pytest-cache
#           - pytest-subtests
#           - pytest-pylint
#         state: latest
