---
- name: Install ZSH
  become: true
  ansible.builtin.apt:
    name: zsh
  tags: &tags_for_zsh_tasks [ 'install', 'productivity', 'dotfiles', 'zsh' ]

- name: Change shell to zsh
  become: true
  user:
    name: "josh"
    shell: /bin/zsh
  tags: *tags_for_zsh_tasks

- name: Check that oh-my-zsh exists
  stat:
    path: /home/josh/.oh-my-zsh
  register: oh_my_stats
  tags: *tags_for_zsh_tasks

- name: Install Oh-My-Zsh
  shell: curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | bash -s -- --unattended
  tags: *tags_for_zsh_tasks
  when: oh_my_stats.stat.exists == False
  become_user: josh

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags: *tags_for_zsh_tasks
